all:
	g++ -o multi-thread-example multi-thread-example.cc -I../src -lpthread -L../lib/ -llog
	g++ -o single-thread-example single-thread-example.cc -I../src -lpthread -L../lib/ -llog
clean:
	rm multi-thread-example single-thread-example
